language: node_js
dist: trusty
sudo: false
node_js:
- '6'
services:
- docker
before_install:
- cp examples/components/* components/
- cp examples/spec/* spec/
before_script:
- docker -v
- docker-compose -v
- docker-compose up -d
