version: '2'
services:
  mqtt:
    image: ansi/mosquitto
    container_name: msgflo-project-mosquitto
    ports:
      - '0.0.0.0:3883:1883'
    entrypoint: /usr/local/sbin/mosquitto
  msgflo:
    image: 0x1d/msgflo-project
    build: .
    container_name: msgflo-project
    environment:
      MSGFLO_BROKER: 'mqtt://mqtt:3883'
    ports:
      - '0.0.0.0:3569:3569'
    links:
      - mqtt
